version: '3'
services:
    ################ OCB ################
    orion:
        hostname: orion
        image: fiware/orion:latest
        ports:
            - '1026:1026'
        depends_on:
            - mongo
        #command: -dbhost mongo
        entrypoint:
            /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -statCounters -dbhost mongo -logForHumans -logLevel
            DEBUG -t 255
        logging:
            driver: 'json-file'
            options:
                max-file: '5'
                max-size: '10m'
    mongo:
        hostname: mongo
        image: mongo:3.4
        volumes:
            - orion_mongo_data:/data/db
            - orion_mongo_conf:/data/configdb
        command: --nojournal
        logging:
            driver: 'json-file'
            options:
                max-file: '5'
                max-size: '10m'

    ################# CBO2INFLUX AND INFLUXDB #############
    cbo2influx:
        hostname: cbo2influx
        image: juanjofranco/cbo2influx
        ports:
            - '8889:8889'
        environment:
            - HTTP_HOST=0.0.0.0
            - INFLUX_HOST=http://influxdb
            - INFLUX_PORT=8086
            - INFLUX_ORG=myorg
            - INFLUX_BUCKET=mybucket
            - INFLUX_TOKEN=1apeD-rqRprWCsiGFN6I15yQhZrCJK3gRFgjfOnqRc0M8z0q0WU5qcGgiZ_VgWiDu_6BjkH5mhKnYaFJjVKjMw==
    influxdb:
        image: influxdb
        ports:
            - 8086:8086
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=juanjo
            - DOCKER_INFLUXDB_INIT_PASSWORD=juanjofp
            - DOCKER_INFLUXDB_INIT_ORG=overtel
            - DOCKER_INFLUXDB_INIT_BUCKET=centic
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=1apeD-rqRprWCsiGFN6I15yQhZrCJK3gRFgjfOnqRc0M8z0q0WU5qcGgiZ_VgWiDu_6BjkH5mhKnYaFJjVKjMw==

    cbo2influx_v1_7:
        hostname: cbo2influx17
        image: juanjofranco/cbo2influx
        ports:
            - '8891:8889'
        environment:
            - HTTP_HOST=0.0.0.0
            - INFLUX_HOST=http://influxdb17
            - INFLUX_PORT=8086
            - INFLUX_DATABASE=mydatabase
            - INFLUX_TOKEN=juanjo:juanjofp
        logging:
            driver: 'json-file'
            options:
                max-file: '5'
                max-size: '10m'
    influxdb17:
        image: influxdb:1.7.11-alpine
        hostname: influxdb17
        ports:
            - 8087:8086
        environment:
            - INFLUX_DB=mydatabase
            - INFLUXDB_USER=juanjo
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=juanjo
            - INFLUXDB_ADMIN_PASSWORD=juanjofp
        volumes:
            - influxdb-storage17:/var/lib/influxdb

volumes:
    orion_mongo_data:
    orion_mongo_conf:
    grafana_data:
    influxdb-storage:
    influxdb-storage17:
